### ISSUE TITLE
init without schema?

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/pipestat#1]
Currently `PipestatManager` requires a pipestat schema to be provided either as an argument or in a pipestat configuration file. Therefore it is impossible to use pipestat solely for the pipeline status monitoring.

**Comment by nsheff** [comment]
might also want to just let people init the schema on the fly, even just for reporting stuff... so like, you init without a schema, but then on first report you have to specify the type (or, it just assumes you mean a string?).

**Comment by stolarczyk** [comment]
This would definitely be convenient, but I'm not sure I like this idea. I view the requirement to predefine results and therefore the possibility to rely on the schema to gather all the possible results metadata in the pipestat users (also software) as a big selling point. 
This would be impossible unless pipestat wrote to the output schema as user reports the new result.

**Comment by nsheff** [comment]
Yeah, you're probably right, better to just require it. I just wonder if it creates too much of a barrier to require people to create a standalone schema for very simple use cases.
