### ISSUE TITLE
Dividing database-dependent pytests

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#104]
As discussed in infrastructure meeting, we I think we should divide out tests with external dependencies. we could possibly:

- use `skipif` to only run a set of tests if database is present
- use a custom option like https://stackoverflow.com/questions/47559524/pytest-how-to-skip-tests-unless-you-declare-an-option-flag to turn on tests.

The goal is that a user can get all information needed by just running `pytest` alone.

**Comment by nsheff** [comment]
See #107

**Comment by donaldcampbelljr** [comment]
This was resolved with #107
