### ISSUE TITLE
Setting indexes in the sqlmodel tables automatically

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#105]
In https://github.com/databio/bbconf/issues/19 I raised a point about how we were selecting based on a non-identifier column, and how this therefore needed an index.

I had to manually add the index in the postgres server, which isn't ideal... it would be better if any necessary indexes could be specified in the json schema.

I'd recommend adding an `index: true` parameter option, and then when we read the schema, automatically setting the indexes on those columns.

**Comment by donaldcampbelljr** [comment]
Currently, `id` is the primary key:
```
 Field(default=None, primary_key=True),
```

For indexing other definitions, I believe the syntax is:
```
 Field(default=None, index=True)
```
So `parsed_schema` should be able to add this if it is detected in the output schema. Should happen here:

https://github.com/pepkit/pipestat/blob/6301b860ac301f0313ac06c661750cb7f589462a/pipestat/backends/db_backend/db_parsed_schema.py#L135-L164

**Comment by donaldcampbelljr** [comment]
This functionality was added in v0.8.0. Closing this issue.
