### ISSUE TITLE
Use RecordNotFoundError exception when record is not found.

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#115]
In many places, I'm finding that `retrieve_one` will return `None` if the record_identifier is bad.

It would be more convenient for me if it would raise a `RecordNotFoundError` (which already exists), and I think is what this exception type was meant for. Then I can catch this and return a coherent message to the user.  With just returning "none" silently, I'm having to build more error handling code.

I think there are several places that it just returns `None` -- maybe these should instead raise appropriate exceptions?

**Comment by donaldcampbelljr** [comment]
Fixed:
https://github.com/pepkit/pipestat/commit/363a54c74008ff7e4c115d0f8ec00e88d2c8debd

**Comment by donaldcampbelljr** [comment]
Closed via https://github.com/pepkit/pipestat/pull/92
