### ISSUE TITLE
Make sure pipestat 0.6.0 is working with Refgenie

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#124]
Refgenie is using pipestat, and before releasing pipestat, we have to be sure, that everything working correctly

**Comment by donaldcampbelljr** [comment]
It looks like this might be more relevant to pypiper. And it appears that we are not doing a lot with pypiper (not reporting which uses pipestat):
https://github.com/refgenie/refgenie/blob/4fb3cbe2c2f4c495444b3d41aa581386ef91ab03/refgenie/refgenie.py#L339-L427

**Comment by donaldcampbelljr** [comment]
Closing for now given above discussion.
