### ISSUE TITLE
naming of optional dependency packages

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#129]
It bothers me a little that the backend optional dependency package is named `db-backend`, because python packages and modules can't have hyphens in them.

It works to have the hyphen in there, since this isn't a module or package... but still, it caused me some problems because when it wasn't working, I thought it might be due to that.

I think it would be better to have a one-to-one correspondence between optional dependency name and module name. Since we call the module `dbbackend` in the code, I think the optional dependency name should correspond, and be `dbbackend`.

what do you think?

**Comment by donaldcampbelljr** [comment]
I implemented this change in dev last week:
https://github.com/pepkit/pipestat/commit/81ca9f2abb5141210cc02ac112eb2acfa04eaa36

**Comment by nsheff** [comment]
thanks.

**Comment by donaldcampbelljr** [comment]
Closed via https://github.com/pepkit/pipestat/pull/92
