### ISSUE TITLE
Pypiper + pipestat: minimal dependencies set

### ISSUE THREAD

**Issue by vreuter** [pepkit/pipestat#143]
Hello @donaldcampbelljr it seems like there's been optionality added to SQL-related (and perhaps other dependencies). Can you advise now on the versions and installation syntax to get the bare minimal set of dependencies needed to use pypiper? This would allow me to update from pypiper 0.12.3 to 0.14.0. In particular, I guess pypiper 0.14.0 --> pipestat >= 0.6. Looking at the setup.py, it seems like this will avoid pulling the SQL-related dependencies, using only requirements-all.txt.

My questions are...
1. Is the above description/assessment right?
2. If so, is it stable to use `pypiper` (not calling anything from `pipestat` directly), without the SQL dependencies? Asking b/c of #116 

Thanks in advance!

**Comment by donaldcampbelljr** [comment]
Hey @vreuter, Yes, your assessment is correct. Pypiper should only install the base pipestat package without SQL dependencies. And it should be stable to use as Pypiper is using pipestat to report to a file backend.

**Comment by vreuter** [comment]
Cool, thanks @donaldcampbelljr !
