### ISSUE TITLE
Why this output schema format?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#16]
The pipestat output schema (also sometimes referred to as the pipestat schema) defines the possible "results" that pipestat can report for a given pipeline. I believe it is required.

My question is: the format for it looks like it's just an array of results. Could this possibly just be made into a json-schema?

Put another why: Why is the output schema format defined as its own format, instead of just having it be a json-schema at the top level?

**Comment by nsheff** [comment]
@stolarczyk I was just looking through pipestat and had this exact same question, again, a year later :).

Any insight here? Why isn't the pipestat schema for outputs just using json-schema in the first place?

**Comment by stolarczyk** [comment]
I guess it didn't make sense to me conceptually to have a _single_ jsonschema to validate _multiple independent results. I'd rather go for a collection of jsonschemas, one per result. 

But you can certainly make it work either way.

**Comment by nsheff** [comment]
I think I see the point now. But am I correct that each of these individual jsonschemas have only 1 property in them then, by definition? So you have a collection of jsonschemas, each with a single property, right?

And the rationale for this is that you want to validate each result independently of the other results?

**Comment by stolarczyk** [comment]
> And the rationale for this is that you want to validate each result independently of the other results?

exactly

> So you have a collection of jsonschemas, each with a single property, right?

yes, that felt too verbose. And that's why pipestat schema became what it is right now. 

In fact it currently is sort of what I suggested above, but in a YAML format. And, under the hood, `jsonchema` is used for validation. Check out [`validate_type` function](https://github.com/pepkit/pipestat/blob/a20bb279fb6d1834057cfcbbddf9c28685d31717/pipestat/helpers.py#L34-L70). 

Therefore jsonschema features (`multipleOf`, `minimum`, etc.) can be embedded in pipestat schema. From the docs:

![image](https://user-images.githubusercontent.com/22797900/217318547-0a56eb3a-4077-4347-8746-19c2f7a9afa8.png)

**Comment by nsheff** [comment]
Do you think it would be possible to maintain the benefits of this approach, but make the main output schema conform to JSON schema?

For example, if we:

1. Make the pipestat schema a proper JSON-schema (not a list of embedded JSON-schemas)
2. To validate a single result, simply subset the `properties` attribute of the primary JSON schema

The benefits of this approach I see are:

1. You can still validate individual results; it just requires pipestat to subset, which shouldn't be too hard anyway
2. Now, to validate an entire pipeline output, I can do it with the JSON-schema as provided. This seems harder to do in the original formulation.
3. Now the pipestat schema is easier to specify -- it's familiar, it's just a JSON-schema, instead of a custom format (even though it's a simple one).
4. This way the pipeline schema could actually be integrated into the [looper output schema](https://looper.databio.org/en/latest/pipeline-interface-specification/#output_schema) -- so in fact you'd just define one output schema and it would work for pipestat/looper.

**Comment by nsheff** [comment]
@stolarczyk I would appreciate any insight/objections from you before we do this, if you have any.

**Comment by nsheff** [comment]
Ok, we will do this. Closing this brainstorming issue in favor of #20
