### ISSUE TITLE
refactor `replace_JSON_refs` function

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#169]
Refactor `replace_JSON_refs` : change s to actual meaning of the argument and add docstring info what is the difference between `s` and `data`

https://github.com/pepkit/pipestat/blob/22516714cbf2d8f6d37f628f393d5655e0b2fe2e/pipestat/parsed_schema.py#L276-L307

**Comment by donaldcampbelljr** [comment]
Ok, I added clarity via the above commit.
