### ISSUE TITLE
SQLModel and sql achemy use brainstorming

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#17]
this package depends heavily on sqlalchemy

sqlalchemy has a pending 2.0 release, which we may consider updating to.

Alternatively, I think we should check out SQLModel: https://sqlmodel.tiangolo.com/ (which is build on top of sql alchemy, and specifically the asyncio stuff that's getting ready for being released in 2.0)

**Comment by nsheff** [comment]
@stolarczyk have you looked at SQLModel at all? Just curious if you had any thoughts on that.

**Comment by nsheff** [comment]
Also, just a historical question for you, @stolarczyk  -- did pipestat always rely on sqlalchemy, or was it added in at a later stage with a switch to ORM?

**Comment by stolarczyk** [comment]
> @stolarczyk have you looked at SQLModel at all? Just curious if you had any thoughts on that.

No, I haven't had a chance to try it out.

> Also, just a historical question for you, @stolarczyk -- did pipestat always rely on sqlalchemy, or was it added in at a later stage with a switch to ORM?

it used `psycopg2` before.

**Comment by nsheff** [comment]
Closing in favor of #26
