### ISSUE TITLE
Schema validation exception messaging 

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#173]
In Bedboss, I faced with a validation error while uploading results via Pipestat. Unfortunately, the error message provided was not sufficiently clear, making it difficult to pinpoint the specific column/result_identifier responsible for the issue.

![image](https://github.com/pepkit/pipestat/assets/41573628/dc78005e-b923-4486-8649-92697bd0d8b9)

**Comment by khoroshevskyi** [comment]
Path is a key in one of the record_identifiers of result_identifiers, however, we don't know which specific record identifier is causing the error.

**Comment by donaldcampbelljr** [comment]
I've added a new exception that adds clarity to the original validation error message to help aid the user when this occurs.
