### ISSUE TITLE
Update to yacman v1

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#18]
As part of my revamp of yacman, I've adapted pipestat to use yacman 2.

This didn't require too many changes; just a few things related to when files are locked, which now uses a contextmanager exclusively. I was able to successfully convert to yacman 2 and can pass all tests now. This is on the yacman2 branch.

This issue is just to track progress on the conversion.

**Comment by nsheff** [comment]
I'm doing this on the `yacman2` branch in this repo.

**Comment by vreuter** [comment]
> I'm doing this on the `yacman2` branch in this repo.

Now in `dev`

**Comment by nsheff** [comment]
Yeah sorry forgot to post that
