### ISSUE TITLE
Add pipestat summarizer or report builder functionality

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#23]
Pipestat creates and reads statistics.

Next, it should also be able to build nice reports from those statistics. 

This is the spin-off of the looper summarizer: https://github.com/pepkit/looper/issues/242

This functionality should be part of pipestat, so it's independent of looper.

**Comment by donaldcampbelljr** [comment]
Currently, looper has `looper report` which builds an html report via a class `HTMLReportBuilder` in `html_reports_pipestat.py`.

**Proposal:**
-create new function `summarize` in Pipestat which could be invoked as `psm.summarize`. It would be agnostic to the type of backend. 
-port the functionality of HTMLReportBuilder to pipestat and tweak it to use the data contained within the Pipestat object and its associated backend.
-deprecate `looper report` functionality

Related to: https://github.com/pepkit/pipestat/issues/20

**Comment by donaldcampbelljr** [comment]
closing with release of v0.5.0
