### ISSUE TITLE
Use SQLModel as interface to database back-end

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#26]
As brainstormed in #17, we want to switch pipestat to using SQLModel under the hood. Here is the vision:

Pipestat takes a schema that describes the outputs of the pipeline, the "pipestat output schema". (updates described in #20).
It allows the `PipestatManager` object to be configured to have either a `yaml` or `SQL` back-end. Currently, the SQL back-end is defined in a pipestat-specific format. Instead, we will switch to using SQLModel to manage the SQL back-end. The yaml backend can stay as is for now. This will allow pipestat to work with any database (not just postgres as currently).

I think the way to implement this would be:

- We are using JSON-schema to describe the schema of the pipeline outputs
- Somehow, we need to use the JSON-schema to build SQLModel classes in Python (is there a built-in way already in SQLModel to do this?)
- As SQLModel classes, these classes will also be Pydantic models and sqlalchemy models
- We can then use SQLModel (via sqlalchemy) to insert instances of the class into a database. This will take over a lot of the current database-handling code in the old pipestat.
- We can *probably* also convert pipestat YAML reading/writing to use SQLmodel objects. Basically, we could use yacman to read/write SQLModel objects to/from yaml files. Yacman would handle all the file locking, etc.

**Comment by nsheff** [comment]
I worked a bit more on this and found a few things. It looks like it will be possible to go from the JSON schema to dynamic SQLmodel objects. Some related things:

https://github.com/pydantic/pydantic/issues/643   -- talks about doing this with Pydantic (not SQLModel). [this comment](https://github.com/pydantic/pydantic/issues/643#issuecomment-583344600) in particular raises two approaches. THe first approach is to [generate actual Python code as done here](https://github.com/koxudaxi/datamodel-code-generator). I prefer the second way, which is to use [dynamic model creation[(https://docs.pydantic.dev/usage/models/#dynamic-model-creation)

I found 2 examples for how to do this with SQLModel:

- https://github.com/tiangolo/sqlmodel/issues/508
- https://stackoverflow.com/questions/74186458/how-to-dynamically-define-an-sqlmodel-class

I took some of these ideas and came up with a demo implementation, which I pushed to the repo as `demo.py` that uses `test/demo_pipestat_output_schema.yaml` as an example schema. The Python code is pasted here for convenience: 

```Python
import yacman

from typing import Optional

from pydantic import create_model
from sqlmodel import Field, Session, SQLModel, create_engine, select

yam = yacman.YAMLConfigManager(filepath="tests/demo_pipestat_output_schema.yaml")

yam
yam.to_dict()


# Create the table column definitions matching this schema
sample_field_definitions = {
	"id": (Optional[int], Field(default=None, primary_key=True)),
}
for element in yam["properties"]["samples"]["items"]["properties"]:
	sample_field_definitions[element] = (Optional[str], Field(default=None))

project_field_definitions = {}
for element in yam["properties"]:
	if element == "samples":
		continue
	project_field_definitions[element] = (Optional[str], Field(default=None))

# Build a SQLModel for this JSON-schema
Sample = create_model(
	f"{yam['pipeline_id']}_sample", # Name of table
	__base__=SQLModel,
	__cls_kwargs__={"table": True},  # Specifies this for SQLModel table
	**sample_field_definitions
	)

Project = create_model(
	f"{yam['pipeline_id']}_project",
	**project_field_definitions
	)


sample_instance = {"smooth_bw":"path/to/smooth_bw.bw"}
project_instance = {"number_of_things": 15}


## Create an instance like this:
p1 = Project(**project_instance)

s1 = Sample(**sample_instance)
s1.smooth_bw

# or like this:
Sample(smooth_bw="path/to/smooth_bw.bw")

# Set attributes like this
p1.counts_table = "25"
p1

isinstance(s1, SQLModel)
isinstance(p1, SQLModel)


# Test database insertion

sqlite_url = "sqlite:///test.db"
engine = create_engine(sqlite_url, echo=True)
SQLModel.metadata.create_all(engine)
session = Session(engine)
s1 = Sample(**sample_instance)
s2 = Sample(**sample_instance)
type(s1)
session.add(s2)
session.commit()
session.refresh(s2)
print(s1)
print(s2)



# Retrieve a sample from the database like this
session.get(Sample, 2)

# Get all the samples from the database
session.exec(select(Sample)).all()

# A generator that iterates through samples
def sample_iter():
	...

```

**Comment by nsheff** [comment]
A few thoughts this brings up:

- should this actually be the way @Khoroshevskyi 's `pepdbagent` works for Sample and Project objects?
- should this actually be the way `peppy` even works for sample and project objects?
- does it make sense to separate Project and Sample objects like this?
- would it make sense to forget the yaml-style back-end of pipestat and just use sqlite for a file-based back-end? it would simplify things...
- would we link projects to samples through relations?

**Comment by nsheff** [comment]
One of the issues this is raising is the difference between schema'd (table-like) and schemaless (document-like) data. The PEPhub interface with pepdbagent is using a schemaless approach. The above is a schema'd approach. Using schemas like this makes a different table for each project (or at least for each pipeline), while the schemaless approach is more flexible.

This above approach seems impractical for all of pephub, since each table in pephub could have a different schema.
But it makes more sense for pipeline *outputs*, -- or basically when a table is tied to a pipeline.

**Comment by donaldcampbelljr** [comment]
**Current Pytest warnings include:**
```
tests/test_pipestat.py: 45 warnings
  /home/drc/GITHUB/pipestat/pipestat/pipestat/parsed_schema.py:271: RuntimeWarning: fields may not start with an underscore, ignoring "__table_args__"
    return create_model(

tests/test_pipestat.py: 43 warnings
  /home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/sqlmodel/main.py:369: SAWarning: This declarative base already contains a class with the same class name and module name as pydantic.main.test_pipe__project, and will be replaced in the string-lookup table.
    DeclarativeMeta.__init__(cls, classname, bases, dict_used, **kw)

tests/test_pipestat.py: 41 warnings
  /home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/sqlmodel/main.py:369: SAWarning: This declarative base already contains a class with the same class name and module name as pydantic.main.test_pipe__sample, and will be replaced in the string-lookup table.
    DeclarativeMeta.__init__(cls, classname, bases, dict_used, **kw)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

```

**Comment by donaldcampbelljr** [comment]
Regarding the remaining warnings:
```
tests/test_pipestat.py: 43 warnings
  /home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/sqlmodel/main.py:369: SAWarning: This declarative base already contains a class with the same class name and module name as pydantic.main.test_pipe__project, and will be replaced in the string-lookup table.
    DeclarativeMeta.__init__(cls, classname, bases, dict_used, **kw)

tests/test_pipestat.py: 41 warnings
  /home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/sqlmodel/main.py:369: SAWarning: This declarative base already contains a class with the same class name and module name as pydantic.main.test_pipe__sample, and will be replaced in the string-lookup table.
    DeclarativeMeta.__init__(cls, classname, bases, dict_used, **kw)
```

This appears to stem from the fact that the SQLModel metaclass is persistent during our pytest testing and contains the tablenames from the previous pytest:
![image](https://github.com/pepkit/pipestat/assets/125581724/299e3ddf-8587-4f4e-9787-d0666d16861a)

In the next test, we create ORMs with the same names, so we get a warning that they already exist.

```
with ContextManagerDBTesting(db_url) as connection:
    psm = pipestat.PipestatManager(
        schema_path="sample_output_schema.yaml",
        #namespace="test",
        record_identifier="constant_record_id",
        database_only=True,
        config="drcdbconfig.yaml",
    )
    psm.report(values=val[0], strict_type=False, project_level=False)


with ContextManagerDBTesting(db_url) as connection:
    psm2 = pipestat.PipestatManager(
        schema_path="sample_output_schema.yaml",
        #namespace="test",
        record_identifier="constant_record_id",
        database_only=True,
        config="drcdbconfig.yaml",
    )
    val = [{"name_of_something": "test_name"},
           {"number_of_things": 1},
           {"percentage_of_things": 10.1}]
    psm2.report(values=val[0], strict_type=False, project_level=False)
```

In the above example, the warning will fire when `psm2` is created since SQLModel still contains the tablenames from the creation of `psm`.

We see this warning fire over and over during pytesting because we create many new pipestatmanger objects during testing that all end up sharing the SQLModel metaclass.

**Comment by donaldcampbelljr** [comment]
```
tests/test_pipestat.py: 45 warnings
  /home/drc/GITHUB/pipestat/pipestat/pipestat/parsed_schema.py:271: RuntimeWarning: fields may not start with an underscore, ignoring "__table_args__"
    return create_model(
```
The above warning occurs during `create_model` when using `__table_args__={"extend_existing": True}` as an input argument. If `__table_args__={"extend_existing": True}` is instead used during` BaseModel` creation, the functionality is preserved and the warning no longer fires.

**Comment by donaldcampbelljr** [comment]
Because #49 seems to be a benign warning, I don't believe it should block this issue even though it it is related. Therefore, marking this as likely-solved.
