### ISSUE TITLE
Example in docs assumes execution from one level below project root

### ISSUE THREAD

**Issue by vreuter** [pepkit/pipestat#28]
In the "Prepare Environment" section of http://pipestat.databio.org/en/latest/cli/, we have:
```shell
export PIPESTAT_RESULTS_SCHEMA=../tests/data/sample_output_schema.yaml
export PIPESTAT_RECORD_ID=sample1
export PIPESTAT_RESULTS_FILE=`mktemp` # temporary file for results storage
export PIPESTAT_NAMESPACE=test
```
But the first path setting assumes we're a level below the project root; if run from the project root, the file won't be found.

**Comment by donaldcampbelljr** [comment]
The tutorial example found [here](https://pipestat.databio.org/en/latest/cli/) assumes:
1. The user has access (i.e. downloaded) to the tests/data folder on the [pipestat github](https://github.com/pepkit/pipestat) such that they have access to the yaml file `sample_output_schema.yaml`.
2.  They've installed pipestat to their local enviroment and are executing the commands at a sub-folder such that:
/main
 ---/tests/data
 ---/subfolder

The tutorial pulls from `cli.ipynb` in the 'docs_jupyter' folder. If the user downloaded 'doc_jupyter' folder and follows along using the Jupyter Notebook in the 'docs_jupyter' folder by opening a Jupyter Notebook instance and then a terminal in 'docs_jupyter', the steps are correct using `../test/data` assuming the user also downloaded the /tests folder.

The tutorial found at [Use Python API](https://pipestat.databio.org/en/latest/python_api/) also assumes the user has access to tests/data.

**Suggested Fix:**
1. Explicitly direct the user to download the relevant .yaml file and create a directory before beginning configuration in the CLI OR 
2. Direct the user to download the repository and navigate to the jupyter_docs folder to follow along with the API and CLI tutorials and **state that the tutorial assumes** one is running from that sub-directory.

For example, for Fix Option 1, add new sub-section in 'Getting Started' titled 'Quick Start':

1. Introduction
3. Install and Configure
4. Quick Start

In the Quick Start section:

1. Assuming you've installed pipestat via Install Configure: [here](https://pipestat.databio.org/en/latest/install/).
2. Make a new folder to configure and run pipestat: 
`mkdir pipestattest`
`cd pipestattest`
3. Make a new data folder to contain data results: `mkdir data`
5. Download the 'sample_output_schema.yaml'  to the current pipestat folder using: `https://github.com/pepkit/pipestat/blob/master/tests/data/sample_output_schema.yaml`

Now we resume the current How-to-Guides with updated path references.
```
rm ./data/test_results_1.yaml
touch ./data/test_results_1.yaml
pipestat report \
    --namespace pipeline_name \
    --record-identifier sample_name \
    --result-identifier percentage_of_things \
    --value 12 \
    --results-file ./data/test_results_1.yaml \
    --schema sample_output_schema.yaml
```

**Comment by donaldcampbelljr** [comment]
Added documentation changes to new branch to clarify that the user should obtain or create output yaml files to follow along with the tutorial:
https://github.com/pepkit/pipestat/commit/fabf0ebd550905f3f2abb88f93bb7f50bc7d8d40
