### ISSUE TITLE
Default logging format makes it difficult to see what's output and what's logs

### ISSUE THREAD

**Issue by vreuter** [pepkit/pipestat#29]
@nsheff maybe a `logmuse` issue, but something that could be modified there or on a per-project basis, but the current (default?) log message format has no formatting template to differentiate it from actual command output. What about adding some basic formatting to log messages to make them look like log messages to make it more clearly, instantly obvious visually what's logging and what's actual output?

Here's an example from running an example in the CLI docs:
```shell
(pipestat) vince@vr-think:~/code/pipestat$ pipestat report -i number_of_things -v 100
Value for the required 'status_schema_path' argument could not be determined.
Value for the required 'flag_file_dir' argument could not be determined.
Writing to locked data...
TEST HERE
Reported records for 'sample1' in 'test' namespace:
 - number_of_things: 100
test:
  sample1:
    number_of_things: '100'


False
sample1
```

**Comment by nsheff** [comment]
Can you clarify what you mean by "actual command output" ?

I think you wrote logmuse originally :). The way I've been using it is that I use it to create the actual command output, I think, if I understand the words correctly.

**Comment by vreuter** [comment]
> Can you clarify what you mean by "actual command output" ?

I meant results from something like `retrieve`, i.e. some sort of text representation of a "result" a user's expecting, rather than log messages emitted along the path to that result.

**Comment by vreuter** [comment]
> Ok I think I misunderstood. I think it should be fine to change the default as you suggest. this probably belongs with logmuse, though

Sounds good. I would transfer the issue directly, but it appears it's not possible, I guess maybe b/c it's under `databio` Github org?

**Comment by donaldcampbelljr** [comment]
I believe the original issue has been solved with the addition of passing a `result_formatter` function per PR: https://github.com/pepkit/pipestat/pull/60
