### ISSUE TITLE
improved error message

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#3]
If I'm a naive user and just testing things out, my first inclination, without reading docs, is to do somethign like this:

```
pip install pipestat
pipestat report -i myval -v 123
```

The error I get is this:

```
pipestat report -i myval -v 123
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/pipestat", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/cli.py", line 28, in main
    psm = PipestatManager(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/pipestat.py", line 142, in __init__
    self[NAME_KEY] = _select_value(
  File "/home/nsheff/.local/lib/python3.8/site-packages/pipestat/pipestat.py", line 112, in _select_value
    raise PipestatError(
pipestat.exceptions.PipestatError: Value for the required 'namespace' argument could not be determined. Provide it in the config or pass to the object constructor.
```

I think it should instead say something like "No config file provided. you must provide a pipestat config file" or something.

**Comment by nsheff** [comment]
related, since the config is required to run pipestat, maybe should be explalined here:

http://pipestat.databio.org/en/latest/install/

**Comment by stolarczyk** [comment]
Ok, I'll need to work on messaging in the CLI. In general, the config isn't required, e.g:

```
In [1]: import pipestat                                                                              

In [2]: psm = pipestat.PipestatManager(namespace="test", results_file_path="/Users/mstolarczyk/Deskto
   ...: p/testing/test.yml")                                                                         
Initializing results file '/Users/mstolarczyk/Desktop/testing/test.yml'

In [3]: print(psm)                                                                                   
In [1]: import pipestat                                                                              

In [2]: psm = pipestat.PipestatManager(namespace="test", results_file_path="/Users/mstolarczyk/Deskto
   ...: p/testing/test.yml")                                                                         
Initializing results file '/Users/mstolarczyk/Desktop/testing/test.yml'
```

it _is_ required if a DB is the backend because that's the only way to provide the login credentials.

**Comment by vreuter** [comment]
@nsheff can you provide more clarity about the relationship between writing to database and writing to file? I've been looking at this, and it's not yet clear if these are mutually exclusive, and which things are conditional on using the database as a backend, and even how using a database as a backend is determined. Is it exclusively by presence of a `config` (file or mapping)? If so, I think that should be renamed to be more indicative of the fundamental backend change that providing a value there is effecting.

**Comment by vreuter** [comment]
^^From the end of `PipestatManager.__init__`, particularly the `if/elif/else` block, it looks like the database and file as backend are indeed mutually exclusive. I'm not sure, however, how to use this in the resolution of this issue, as the relationship between calling `_select_value` to try to get "namespace" (as is where the error in this issue occurs) and the presence / absence of a config file is unclear.

**Comment by nsheff** [comment]
> @nsheff can you provide more clarity about the relationship between writing to database and writing to file? I've been looking at this, and it's not yet clear if these are mutually exclusive, and which things are conditional on using the database as a backend, and even how using a database as a backend is determined. Is it exclusively by presence of a `config` (file or mapping)? If so, I think that should be renamed to be more indicative of the fundamental backend change that providing a value there is effecting.

database and file back-end are mutually exclusive. You just choose one. pipestat provides an interface that can read and write from either of them. I think the config file specifies which you are doing

**Comment by nsheff** [comment]
> @nsheff what do you think about this?
> 
> pipestat.exceptions.PipestatError: Could not determine value for namespace. This may be passed directly to the pipestat manager constructor, or through a configuration file, or as an environment variable: PIPESTAT_NAMESPACE
> ```

This seems very developer-oriented.

I would think some kind of messaging that says "back-end not specified" would make more sense here

**Comment by vreuter** [comment]
> I would think some kind of messaging that says "back-end not specified" would make more sense here

I don't see how the two things (one being this error, the other being the lack of specification of a back-end) are related. This error appears to happen when two things are jointly true:
a) `namespace` is _not_ passed directly to the constructor of the `PipestatManager`
b) The `namespace` can be determined neither from the config file nor from the environment variable.

To me, it seems that at this point in the logic, where the error's occurring, there's not yet been any inspection of whether a results file path is available (which seems to signal use of the file as backend, rather than database); specifically, nothing at this point (where the error's occurring) in the logic of the constructor has dealt with the value of `results_file_path`.

What am I missing?

**Comment by vreuter** [comment]
^^ @nsheff perhaps I don't yet fully understand the different ways in which a config file could be formatted / used, but the error here seems to be just related to retrieval of a specific value from either the environment or the config file; it seems to me like a user encountering this may well have passed a value for `results_file_path`, thereby specifying a backend (to file).

**Comment by donaldcampbelljr** [comment]
This still needs improvement:
```
(env) drc@databio:~/virtual_envs/pipestat_venv_dev$ pipestat report -i myval -v 123
Traceback (most recent call last):
  File "/home/drc/virtual_envs/pipestat_venv_dev/env/bin/pipestat", line 5, in <module>
    from pipestat.__main__ import main
  File "/home/drc/virtual_envs/pipestat_venv_dev/env/lib/python3.10/site-packages/pipestat/__init__.py", line 8, in <module>
    from .pipestat import *
  File "/home/drc/virtual_envs/pipestat_venv_dev/env/lib/python3.10/site-packages/pipestat/pipestat.py", line 13, in <module>
    from pipestat.backends.filebackend import FileBackend
ModuleNotFoundError: No module named 'pipestat.backends'
```

**Comment by nsheff** [comment]
that looks like a more fundamental problem about the organization of the package.

**Comment by donaldcampbelljr** [comment]
Thank you. I fixed that underlying issue and was able to attempt this again:
```
(venv) drc@databio:~/GITHUB/pipestat/pipestat$ pipestat report -i myval -v 123
Using default config. No config found in env var: PIPESTAT_CONFIG
Config: None.
Traceback (most recent call last):
  File "/home/drc/GITHUB/pipestat/pipestat/venv/bin/pipestat", line 8, in <module>
    sys.exit(main())
  File "/home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/pipestat/cli.py", line 36, in main
    psm = PipestatManager(
  File "/home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 80, in __init__
    self.process_schema(schema_path)
  File "/home/drc/GITHUB/pipestat/pipestat/venv/lib/python3.10/site-packages/pipestat/pipestat.py", line 216, in process_schema
    raise SchemaNotFoundError("PipestatManager creation failed; no schema")
pipestat.exceptions.SchemaNotFoundError: Results schema not found. The schema is required to PipestatManager creation failed; no schema. It needs to be supplied to the object constructor or via 'PIPESTAT_RESULTS_SCHEMA' environment variable.

```

**Comment by nsheff** [comment]
ok, that's not perfect, but still much better than it was.

Question: Is a config file *required* if pipestat is used through the CLI? Well, no -- not if "results_file" is provided.

But in this case, neither config file nor results file is provided, and that seems like the real problem.

**Comment by donaldcampbelljr** [comment]
```
/home/drc/GITHUB/pipestat/pipestat/venv/bin/python -m pipestat report -i number_of_things -v 100 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/drc/GITHUB/pipestat/pipestat/pipestat/__main__.py", line 7, in <module>
    sys.exit(main())
  File "/home/drc/GITHUB/pipestat/pipestat/pipestat/cli.py", line 44, in main
    raise PipestatStartupError(msg)
pipestat.exceptions.PipestatStartupError: Either a config file or a results file must be provided. Either must be supplied to the object constructor or via environment variable. 
Please see: http://pipestat.databio.org/en/dev/cli/
```
