### ISSUE TITLE
Customizing location of flag files in the results_pipeline dir

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#34]
Right now, `project.results_pipeline` is used as the subdir within the `project.output_dir`. Looper then adds the sample name on to the end of this folder automatically, and then looks there for flags and summarizer files

The refgenie pipeline shows that we need more flexibility. We're setting up the pipeline to place flags and outputs in a much deeper folder (so we can exclude it from archive checksumming, etc). But there's no way to tell looper about this, and hence, flag checks and summarizers will never work with this pipeline.

This could be solved by making the 'results_pipeline' + {sample.name} hard-coding into a template that can be populated with sample properties, which should point directly to the output folder. 

Related to pepkit/looper#242

**Comment by nsheff** [comment]
I think this might make sense to add as an attribute in the pipestat schema, maybe under the `status` components?

Or wait, would it make more sense to add to the looper pipeline interface (maybe I moved it from looper to pipestat prematurely...)

**Comment by donaldcampbelljr** [comment]
Currently, the user can pass `flag_file_dir` to the PipestatManager class during initialization or provide the directory in the config file.

Then, pipestat determines:
```
  flag_file_dir = self[CONFIG_KEY].priority_get(
      "flag_file_dir", override=flag_file_dir, default=os.path.dirname(self.file)
  )
  self[STATUS_FILE_DIR] = mk_abs_via_cfg(flag_file_dir, self.config_path)
```
