### ISSUE TITLE
Tests should stand alone

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#38]
Right now, tests depend on previous tests.

Instead, tests should be runnable independently.

**Comment by donaldcampbelljr** [comment]
Tests in test_pipestat.py still rely on each other.

**Comment by nsheff** [comment]
did the context managers solves some of it?

**Comment by donaldcampbelljr** [comment]
Yes, but mostly for DB testing in `test_db_only_mode.py`

**Comment by donaldcampbelljr** [comment]
https://github.com/pepkit/pipestat/pull/36/commits/1262f2104f5a977c78775478bf23672583764ea8

https://github.com/pepkit/pipestat/pull/36/commits/5a552c58ff9e7f881ff0e63e5358960a293c8afc

To do:
1. Add remaining functionality ( a couple of tests need to test after an 'else' statement to be more thorough).
2. Remove any redundancy (consolidate where possible)

**Comment by donaldcampbelljr** [comment]
To do:
- `test_custom_status_schema` needs to be re-implemented.

**Comment by donaldcampbelljr** [comment]
To do:
- implement a way to test for clearing status.
