### ISSUE TITLE
User interface and .data

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#39]
Right now, there's a `.data` interface to a PSM object, where you can see the results that were reported across records.

In the past, it would be populated and managed by pipestat, even when backed by a db.

With change to sqlmodel, this went away, and so tests and this interface are broken.

The important principle is that the User API should be the same regardless of back-end. But, now using sqlmodel, we don't really want to have local in-memory representations of things, we want to retrieve from the db. So, we need some way to show the data that works for both back-ends.

Two possible solutions:

1. Some new class that uses dict accessors, and translates those into .retrieve queries
2. deprecate a `.data` interface that expects nested dict objects; instead, use `.retrieve` or implement `.list()` or something else that can work with both.

I'm leaning toward option 2

**Comment by donaldcampbelljr** [comment]
Pytests failures regarding this issue have been rectified but the proposed solutions have not yet been implemented.
