### ISSUE TITLE
pipestat init

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#4]
Do you think it would be useful to have a `pipestat init` that would create a skeleton config for you, given a few CLI options? otherwise what's the recommended protocol for creating a config?

**Comment by stolarczyk** [comment]
yeah, we could add `init`, but I thought documenting the config format was enough: http://pipestat.databio.org/en/latest/config/

**Comment by nsheff** [comment]
init is nice for tutorials... then to show someone how to set up I can say, "paste this":

```
pipestat init -c my_config.yaml ...
pipestat report ...
```

it's a much easier lift than "go to this page and read all this text, and copy+paste this file but change X, Y, and Z...
