### ISSUE TITLE
wrap database-related dependencies?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#64]
Does it make sense to wrap sql-related dependencies of pipestat into some kind of try/catch and not force them to be installed?

As noted here: https://github.com/databio/pypiper/issues/184

For someone who's only ever intending to use pipestat as a file back-end, they wouldn't need those dependencies.

@vreuter would be interested to hear how you would solve this problem.

**Comment by nsheff** [comment]
I guess a proposal is this:

1. remove sqlmodel and psycopg2-binary dependencies
2. if user configures a db backend, `try` to load them, and fail with an appopriate error message if they don't exist

now pipestat works without those, and prompts if they are not installed with an appropriate error message. Not perfect, since it won't force them to be installed, but could be desirable....

**Comment by nsheff** [comment]
I think this is the way we should do it: https://stackoverflow.com/a/27361558

make the sql backend stuff as `extra-requires` and then put at the init a `try` block that sets a variable as "sql_ready" true or false, then mark the db backend as requiring sql_readty to be true and exit with error if not.

**Comment by donaldcampbelljr** [comment]
Began taking a look at this issue this afternoon:
- was able to move DB dependencies to optional requirements-optional.txt
- Using try/excepts for importing DB dependencies

Obstacle:
-When importing `helpers *`, a parameter is defined `ORM: SQLModel` which will be undefined without importing SQLModel. This is the `dynamic_filter` function which only applies to DB backend actions, so we could move it to another file (`dbbackend.py`).

**Comment by donaldcampbelljr** [comment]
This topic came up again recently with the introduction of https://github.com/pepkit/pipestat/issues/22.

Specifically, we should make it such that using the file backend has the least amount of dependencies installed and if one wishes to use DB backend and/or pipestat reader, one must install those dependencies separately.

**Comment by donaldcampbelljr** [comment]
Working example on branch `dev_move_reader_dependencies`: https://github.com/pepkit/pipestat/commit/5ce2d9392671503857bad68beda209255dfc7ac8

user can install minimal dependencies and execute pipestat. However, if they attempt to use the DB backend, an exception is raised to tell the user how to install optional dependencies.

**Challenges:**
I had to move some DB specific helper functions to a new file.
ParsedSchema is used for both file and db backend, so for this to work, I need to separate DB specific functionality.

**Comment by nsheff** [comment]
nice! That makes sense to me. 

This makes me wonder... it might be worth a bit of a step back to reorganize the file naming to clarify how it works. for example, maybe it makes more sense to do:

```
/db_backend
  backend.py
  helpers.py
/file_backend
  backend.py
  helpers.py
```

instead of the current `backends/` approach. then, each backend is just a submodule, and everything it needs that's special to it would live in that submodule.

**Comment by donaldcampbelljr** [comment]
Yeah! I like this idea and will implement it.
