### ISSUE TITLE
get_model vs get_orm

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#71]
https://github.com/pepkit/pipestat/blob/3dc0074053bb5df4a0cf339f85acc8c0b2a5b35a/pipestat/backends/dbbackend.py#L98-L115

https://github.com/pepkit/pipestat/blob/3dc0074053bb5df4a0cf339f85acc8c0b2a5b35a/pipestat/backends/dbbackend.py#L115-L125

What's the difference between `get_model` and `get_orm`, and why do we need both of these functions?

**Comment by nsheff** [comment]
@vreuter or @donaldcampbelljr do you have any insight here?

Can I just collapse these?

**Comment by donaldcampbelljr** [comment]
It appears to me that these could be collapsed into one function.

**Comment by vreuter** [comment]
It looks like the main logic is the same, just a bit different behavior if `orms` is null, around how error throwing is controlled or not, and what type of error would arise.

**Comment by donaldcampbelljr** [comment]
This is now simplified.
