### ISSUE TITLE
retrieving just one result /attribute

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#72]
In my hands, when I use `retrieve` with a database backend, giving it a `result_identifier` has no effect.

It always gives me back the entire sample, not just the particular attribute I am requesting.

**Comment by donaldcampbelljr** [comment]
I am unable to replicate this issue on my machine using the `pipestat_table` branch. I tried sample and project level reporting and retrieving. 

output:
```
Results when using result_identifier = "project_integer"

100

Results when not using result_identifier

{'project_string': 'misc string to report', 'project_integer': 100, 'project_name': 'random_project_id_2', 'id': 2}
```
Commands:
```
    results8 = psm2.retrieve(project_name="random_project_id_2", result_identifier="project_integer",
                             pipeline_type='project')
    print(results8)

    results9 = psm2.retrieve(project_name="random_project_id_2",
                             pipeline_type='project')
    print(results9)
```

**Comment by nsheff** [comment]
I'm using that branch, for a sample pipeline,and `psm.retrieve("mysample", "result_id")` returns the entire thing; the same as `psm.retrieve("mysample")`. 

So I'm doing: `psm.retrieve("mysample")["result_id"]` and that works,but I should be able to do `psm.retrieve("mysample", "result_id")`. 

I guess I will either create a MWE or just fix it

**Comment by nsheff** [comment]
I'm using database backend

**Comment by nsheff** [comment]
fasinating... `psm.retrieve("mysample", result_identifier="result_id")` works.... so it only works if I *name* that second arg. but it *should* be working without it being named....

**Comment by nsheff** [comment]
Here's a MWE:

```
bbc = BedBaseConf("bedbase.org/config/bedbase2.yaml")

bbc.bed.retrieve("78c0e4753d04b238fc07e4ebe5a02984")  # gives the entire sample

bbc.bed.retrieve("78c0e4753d04b238fc07e4ebe5a02984", "bedfile")  # doesn't work, gives the entire sample

bbc.bed.retrieve("78c0e4753d04b238fc07e4ebe5a02984", result_identifier="bedfile")  # works
```

**Comment by nsheff** [comment]
Ok I figured it. it was very confusing, but the `retrieve` function on the main `PipestatManager` class has a different signature from the one on the backend. I didn't realize that, and I was expecting it to work like that.

We will need to change that signature. I suggest:


- we `PipestatManager.retrieve` expect `record_identifer` instead of `sample_name` and `project_name`, so it can match the backend signature.
- we eliminate the `_get_record_identifier` concept 
- we could handle doing both types using a separate function, if necessary (like, `retrieve_project` to access project-level attributes, instead of overloading retrieve)

**Comment by donaldcampbelljr** [comment]
The input arguments order doesn't match across the pipestat.py retrieve function and the dbbackend version. I assume that's what's causing issues?

**Comment by donaldcampbelljr** [comment]
I'll check the other functions signatures on Monday to ensure consistency.

**Comment by nsheff** [comment]
> The input arguments order doesn't match across the pipestat.py retrieve function and the dbbackend version. I assume that's what's causing issues?

sort of -- it's not so much the order, it's that the signature is not the same (the arguments *differ*).

this will require some rethinking about how to manage project vs sample records, though.

**Comment by donaldcampbelljr** [comment]
I did another pass on the signatures along with some other polishing. This should now be working as expected.
