### ISSUE TITLE
back-ends should use consistent error types

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#74]
Right now, the `retrieve` function on the different backends raises different kinds of errors.

I think this defeats the purpose of the standardized interface.

```
  File "/home/nsheff/.local/lib/python3.11/site-packages/pipestat/backends/dbbackend.py", line 553, in retrieve
    raise PipestatDatabaseError(f"Record '{sample_name}' not found")
pipestat.exceptions.PipestatDatabaseError: Record '78c0e4753d04b238fc07e4ebe5a0298s' not found
```

the file backend raisesa `PipestatDataError`.

These error types leak information about the backend. That ruins the point. 

Instead, these should return error types that relate to the behavior of the error, not to the implementation detail.

In both cases, I think these should be a `RecordNotFound` error. This way, my calling code can catch `RecordNotFound` errors, regardless of the backend. the way it is, now I have to write code that depends on the back-end, which is bad.

In addition to fixing this, we should go through the two backends and ensure that any functions defined in the abstract interface should raise the same types of errors across the two backends

**Comment by nsheff** [comment]
actually this would be a good candidate for a [LookupError](https://docs.python.org/3/library/exceptions.html#LookupError), so we don't have to create our own exception type here.

**Comment by nsheff** [comment]
Or rather, we can define a `RecordNotFound` error that inherits from `LookupError`. that's probably the best way to do it.

**Comment by nsheff** [comment]
@donaldcampbelljr can you prioritize this, this morning?

**Comment by donaldcampbelljr** [comment]
Implementing a more generic `RecordNotFoundError` that inherits from `LookupError`:
```
  File "/home/drc/PythonProjects/pipestat/testimport/venv/lib/python3.10/site-packages/pipestat/backends/dbbackend.py", line 553, in retrieve
    raise RecordNotFoundError(f"Record '{sample_name}' not found")
pipestat.exceptions.RecordNotFoundError: Record 'bogus' not found
```

**Comment by donaldcampbelljr** [comment]
I searched for the errors that could be generalized across the backends and made the above changes. There are some errors that are specific to the backends that I left alone for now, e.g.:
https://github.com/pepkit/pipestat/blob/16346f1e79657ccafd29b5f48a93226cfb3f33b3/pipestat/backends/dbbackend.py#L115-L125

**Comment by nsheff** [comment]
> There are some errors that are specific to the backends 

I think it's just for the functions that are described on the abstract class, they should raise the same errors.
