### ISSUE TITLE
getting a list of samples

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#75]
I'm trying to retrieve a list of what samples (rows, really) are in a table, but I can't figure out how to do it.

it seems I can only use pipestat if I know the identifier of the sample I'm interacting with.

I see in the abstract class there's a `get_samples` signature, but it looks like this was never implemented on the back-end.

I think we need to do this, since this is functionality I now need for bedhost.

**Comment by nsheff** [comment]
There is something called `get_records` defined on the dbbackend.

This or something like it should probably be made generic and elevated to the abstract class. will probably need to implement paging.

**Comment by donaldcampbelljr** [comment]
Added `get_records` to abstract class and PipestatManager so that it can be invoked as `psm.get_records()`

To do:
- [ ] implement pagination
- [ ] potentially rethink the structure of returned list; currently it is a list of tuples because that is what is used for generating the html reports.

**Comment by nsheff** [comment]
@donaldcampbelljr can you prioritize this, implementing paging? 

I would like it if these functions could take `limit` and `offset` parameters, and then return a structure that looks like:

```
{
  "count": x,
  "limit": l,
  "offset": o,
  "items": [...]
}
```

where limit and offset are whatever the user provided (defaults to limit=1000 or something, offset=0), and count is the total number of items in the database.

**Comment by nsheff** [comment]
The `count` is currently implement to return the number of files in the `records` entry.

What I intended was for `count` to return the *number of items in the database*. The point is that it will let you know if there is more to get. If I need the number of items return, I can just count them.

**Comment by donaldcampbelljr** [comment]
Ok, this is now fixed.
