### ISSUE TITLE
Change 'result' to 'attribute' ?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#76]
As I've worked with this more, it's confusing to me to think of "results".

I often find myself just thinking this should be called "attribute". Just a thought that maybe we should change terminology in the code.

**Comment by donaldcampbelljr** [comment]
FWIW, 3.5 months later, I still continue to think of these reported items as `results`.

**Comment by donaldcampbelljr** [comment]
Any more thoughts on this one way or the other? Should we close this out for now?

**Comment by nsheff** [comment]
I'm fine with leaving this as is.
