### ISSUE TITLE
Separate sample and project level pipestat manager objects

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#78]
After some discussion, we have decided to proceed with separating sample and project level PipestatManager objects. This will allow the user to create an object specifically to report sample results or project results. 

For example: currently the user creates an object `psm = PipestatManager()` and must specify the pipeline type and give the object either a `sample_name` or `project_name` to perform actions.

**Plan:**
- PipestatManager will now be an abstract class with two child classes: 1. `PipestatMgrSample` 2. `PipestatMgrProject`

**Some simplification will occur:**
-The backend functions will no longer need to worry about either being given a `sample_name` or a `project_name`, instead we will revert to using `record_identifier`. 
-We will also be able to remove the need for passing `pipeline_type`
-During DBbackend table creation, we will no longer automatically create both a sample and a project table. Instead, the manager object will create either table depending on its type. We will also be able to remove logic to get either a sample or project table, as there will only be one table associated with the manager object.

**Comment by nsheff** [comment]
I'd vote for naming the concrete classes as: `SamplePipestatManager` and `ProjectPipestatManager`

**Comment by donaldcampbelljr** [comment]
I replaced the two functions to build out a `project` or `sample` specific model and replaced it with a single function that will work when either `SamplePipestatManager`or `ProjectPipestatManager` is called. However, if we want to use the same output schema for both a project level and sample level run in the same database (which is where the user typically supplies  the pipeline name), we will need to differentiate their table names. Previously, this was done by:
```    
def _table_name(self, suffix: str) -> str:
        return f"{self.pipeline_name}__{suffix}"
```
Some options:
1. I could re-implement this naming convention by appending the proper suffix to the pipeline name before model creation.
2. The user could supply the pipeline name during `PipestatManager` creation (not in the output schema, but as an input argument to `SamplePipestatManager`).
3. Do we actually **need** separate tables? Is it feasible to put sample and project results (from the same pipeline) into the same table and simply have a column that denotes if they were run at the sample or project level?

**Comment by nsheff** [comment]
Well, sample and project level results will have different schemas.

So, yes, that means they cannot be the same table (table = schema)

**Comment by donaldcampbelljr** [comment]
1.Create wrapper to hold the child clases ala pipestatboss:
so could do pipestatboss.sample.retrieve and we would retain linkage between project and sample level for

2. continue to make table names with the suffixes, we will revisit the idea of customizing table_names.

**Comment by donaldcampbelljr** [comment]
SampleManager and ProjectManager

**Comment by donaldcampbelljr** [comment]
Pipestatmanager(ABC)    
# TODO make this an abstract class 
    # then inherit from mapping?
    # or inherit from mapping and use decorator @abstractmethod for each function

**Comment by donaldcampbelljr** [comment]
Added simple wrapper with this commit:
5df17916576f65beb162144229e1145c81792be2

Usage:
```
    # The output schema has BOTH sample and project level result identifiers
    # User supplies list of pipeline types (right now its only sample and project).

    psb = PipestatBoss(pipeline_list=['sample', 'project', 'not_a_pipeline_type'], schema_path="output_schema.yaml", config_file="pipestat_config.yaml")

    reported_results_sample = psb.SampleManager.report(record_identifier="random_sample_id", values={"number_of_things": 1})

    reported_results_project = psb.ProjectManager.report(record_identifier="random_project_id", values={"project_string": "misc string to report"})

```
At present, PipestatBoss is a very simple class that can contain `ProjectPipestatManager(**kwargs)` and/or `SamplePipestatManager(**kwargs)` as attributes. Nothing inherits from this class or vice versa.

**Comment by nsheff** [comment]
ok, but the names of the attributes shouldn't be capitalized; that's reserved for names of classes (not instances of classes).
