### ISSUE TITLE
Could we specify simple output schema during PipestatManager creation?

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/pipestat#86]
for configuring pipestat, having to specify an output schema is a heavy lift. What if for a simple pipeline, I could specify it right there when I construct the object?

it would look like:
```
psm = pipestat.PipestatManager(
	schema = {"seqcol_digest": { "type": "str"}},
	results_file_path=results_file,
	pipeline_name = "compute_seqcol_digest"
	sample_name= "sample_name"
	)
```
Should we do this?

**Comment by donaldcampbelljr** [comment]
Currently, during schema parsing, we require a `samples` field for sample-level result identifiers. Otherwise, pipestat assumes the user wants the identifiers to be project-level. Related issue and PR:
https://github.com/pepkit/pipestat/issues/20
https://github.com/pepkit/pipestat/pull/65

I propose we create a new parameter, `schema_dict` that can be used in place of `schema_path`, similar to how we currently allow for either `config_file` or `config_dict`.
```
schema_path: Optional[str] = None,
schema_dict: Optional[dict] = None,
```
I would change pipestat to assume that any result identifiers provided without being explicitly stated as sample or project will be assumed to be **sample-level**:
https://github.com/pepkit/pipestat/blob/2790bed3ac3e7487f087a857468ce2084011dc16/pipestat/parsed_schema.py#L93-L98

**Another note:** 
The user must provide the `pipeline_name` (see above example) as an input argument if they only provide the `schema_dict` and not the `schema_path` as the `output_schema.yaml` file is where the user generally provides the `pipeline_name`.

Any other thoughts or concerns @nsheff ?

**Comment by donaldcampbelljr** [comment]
Create schema as a pydantic object and just pass it through and then do json validation?

For now, just use the schema_dict approach?

**Comment by nsheff** [comment]
I noticed you used `project` as the attribute name for the project-level info. In eido, we used `config` as that name. So, these will not be compatible.

I think we should use the same standard. But, I actually like `project` better than `config`. So... what do you think?

**Comment by donaldcampbelljr** [comment]
**You can report results to a filebackend without using a schema.** For dbbackend, one must use a schema.
