### ISSUE TITLE
add limit to retrieve method in PipestatManager 

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#88]
It would be nice to have limit method that allows user to specify limit of the rows that have to be selected from the database.
++
retrieve method has incorrect docstring:
![image](https://github.com/pepkit/pipestat/assets/41573628/2e428bee-b93e-4523-9393-40a6cd445163)

**Comment by donaldcampbelljr** [comment]
Is this still actually an issue? This particular method is for `Retrieving a result for a single record.`

There are other functions that do allow for retrieving multiple rows `select` and `get_records` and they _do_ have `limit` parameters.

**Comment by khoroshevskyi** [comment]
It's not super important, because we can use backend.select. But I would keep this question open

**Comment by donaldcampbelljr** [comment]
This is solved with PR #101
