### ISSUE TITLE
Add `upload_date` and `last_update_date` to pipestat 

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#93]
it would be nice to have this two columns + functionality, where you can select results and filter them by date

**Comment by donaldcampbelljr** [comment]
From our discussion:
-Report creation date/time and modified date/time only at the record level (i.e. two new columns)
-Don't make it optional.

Suggested column names
_pipestat_creation_time
_pipestat_modified_time

Use built-in SQL date object and ISO standard 8610 standard


In sql alchemy/ sql model  -> you can specificy  the timezone, this is a nice to have, not a necessity.

Example Python Code:
```
submission_date=datetime.datetime.now(datetime.timezone.utc),
```
