### ISSUE TITLE
fields may not start with an underscore

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#94]
Not sure if this is a pipestat, bbconf, or bedboss issue, but I'm getting this warning message when I try to run bedboss

```
/home/nsheff/.local/lib/python3.11/site-packages/pipestat/parsed_schema.py:365: RuntimeWarning: fields may not start with an underscore, ignoring "_pipeline_name"
```

**Comment by donaldcampbelljr** [comment]
I found where it was happening in pipestat and have fixed it.
