### ISSUE TITLE
Update `schema` in pipestat

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pipestat#95]
Now code looks like that:
```
    @property
    def schema(self) -> Dict:
        """
        Schema mapping

        :return Parsed: schema that formalizes the results structure
        """
        return self.get(SCHEMA_KEY)
```

And schema actually returning `ParsedSchema` object. But in docstring it says that in should return Dict.
This should be fixed. schema should return either dict, or docstring should be changed

**Comment by donaldcampbelljr** [comment]
This is now fixed in dev: https://github.com/pepkit/pipestat/commit/4be4a9e580d760b326873a34562080d44d690861

**Comment by donaldcampbelljr** [comment]
Closed via https://github.com/pepkit/pipestat/pull/92
