### ISSUE TITLE
what is the pipestat store attribute?

### ISSUE THREAD

**Issue by nsheff** [pepkit/pipestat#99]
the pipestat.PipestatManager has a `store` attribute:

https://github.com/pepkit/pipestat/blob/dev/pipestat/pipestat.py#L90

It appears to be being used to set/get items from a dict: 

https://github.com/pepkit/pipestat/blob/f228c0bcebb8521fc957dba4daedc37f6979d38d/pipestat/pipestat.py#L234-L247

I can't see where this is connected to the backends. What is this store for? Is this a relic that should be removed?

**Comment by donaldcampbelljr** [comment]
This was actually added when we decided to change PipestatManger to inherit from MutableMapping and not dict. Essentially, the above code, has pipestat act like a dict but it is not technically a dict.

**Comment by nsheff** [comment]
Ok, interesting.

What purpose does it serve? It is not connected to the back-end, so this seems just... superfluous.

**Comment by donaldcampbelljr** [comment]
It is so that PipestatManager can store attributes like so:
https://github.com/pepkit/pipestat/blob/f228c0bcebb8521fc957dba4daedc37f6979d38d/pipestat/pipestat.py#L151-L162

https://github.com/pepkit/pipestat/blob/f228c0bcebb8521fc957dba4daedc37f6979d38d/pipestat/pipestat.py#L662-L668

**Comment by nsheff** [comment]
I see. 

I propose we change this so that:

1. For internal metadata, we use a dedicated dict and don't use `getitem` syntax, so the above would be changed to: `self.metadata[FILE_KEY]` and `self.metadata.get(RECORD_IDENTIFIER)`. Since this seems to be for internal use, I'm not sure we need the getitem convenience.
2. We change the `getitem` syntax to actually be an alias for `.retrieve`, and `setitem` to be an alias for `report`. This would be a simplified form, less powerful than using the actual retrieve, but maybe more convenient.

To insert a result then, you'd use `psm["my_result_key"] = my result_value`.

Why? Because then a PipestateManager object is actually a Mapping *of the values it is reporting to the database*. This would allow me to use it in seqcol instead of my RDBDict object.

Alternatively, I could just write a little wrapper around PipestatManager that would do this.

**Comment by nsheff** [comment]
any objection to this @donaldcampbelljr ?

**Comment by nsheff** [comment]
Related to #97

**Comment by donaldcampbelljr** [comment]
No objection. I think this is a cool idea. I can begin implementing it this week.

**Comment by donaldcampbelljr** [comment]
Ok, I have added the discussed changes for this. I opted to use `psm.cfg` instead of `psm.config`.

Changes exist in branch [dev_99_103_API_Refactor](https://github.com/pepkit/pipestat/compare/dev_99_103_API_Refactor)

**Comment by donaldcampbelljr** [comment]
Closed via https://github.com/pepkit/pipestat/pull/92
